# Upload keystore configuration for Google Play Console
# IMPORTANT: DO NOT COMMIT THIS FILE TO GIT!
# This file should be in .gitignore

storePassword=imu2026
keyPassword=imu2026
keyAlias=imu-upload-key
storeFile=upload-keystore.jks
