# yaml-language-server: $schema=https://unpkg.com/@powersync/cli-schemas@latest/json-schema/service-config.json

# PowerSync Cloud config for IMU
# Docs: https://docs.powersync.com/sync/overview

_type: cloud

name: imu-mobile

region: jp

# -------------------------------------------------------------------------
# Replication: PostgreSQL database connection for sync
# -------------------------------------------------------------------------
replication:
  connections:
    - type: postgresql
      uri: postgresql://doadmin:AVNS_70HyRhviU4jC0NA6b16@imu-production-do-user-21438450-0.l.db.ondigitalocean.com:25060/imu_db?sslmode=require
      name: imu-production
      sslmode: verify-ca
      cacert: |
        -----BEGIN CERTIFICATE-----
        MIIEUDCCArigAwIBAgIUMaS20SbRbqIxh5ZtiR3TU5ZDvhIwDQYJKoZIhvcNAQEM
        BQAwQDE+MDwGA1UEAww1YjY1Mjk2M2EtZTA2NC00ZWRiLTg1MzYtMTk3ZjA3NDNk
        NzEyIEdFTiAxIFByb2plY3QgQ0EwHhcNMjUwNzE0MDY0MjQ0WhcNMzUwNzEyMDY0
        MjQ0WjBAMT4wPAYDVQQDDDViNjUyOTYzYS1lMDY0LTRlZGItODUzNi0xOTdmMDc0
        M2Q3MTIgR0VOIDEgUHJvamVjdCBDQTCCAaIwDQYJKoZIhvcNAQEBBQADggGPADCC
        AYoCggGBAMONfo9dN8wBh/sSPwVGVm+sYArJz3j5FA0K9fTa/SDlIP0uBTQX6bPv
        Rft+9hy06AbxkKneP4/Go0ebm+lIiZY88ySduLagyLkLUByJsELJJVgDEjXnI4p1
        xJWlVJZ9Ur7sp+sp3j96WxkHXX+DtEiHFW3wa1OJ/qQ131GxYuAH89OqCDx9Mm3P
        Dq25Waz1u0I6TLZvNCaWcvJbItT1XtqBOBxQ4YKq6Ls9ySeVdWwB6P8bWpthQaRP
        VmG7CgjritPlCcJhBbrERyNOf/j6bfI29pDkrMwFJmhn8NMwyDD41P0hF4YT3j80
        owSc3N+BUcQjvOr/AxPhcseZHwqm2g5gFidqbb5JkiiO5L4FOQSdnRble06uq03k
        ab9WtAqcvx0YCZGgZdtKbvJwcfdd1AMjHphtlkJEZJLQ2/n8Ge+zfe5bqOmqi4zj
        m+v/HSQWTYrrgdSkoW7KB3EWA+tplEZgfga2o9mBpa79mVttiPuNVYjo9o8R0j/U
        pGbCvEuinQIDAQABo0IwQDAdBgNVHQ4EFgQUwwZ0INaSvZJBIK0BJyh4/3pPNL0w
        EgYDVR0TAQH/BAgwBgEB/wIBADALBgNVHQ8EBAMCAQYwDQYJKoZIhvcNAQEMBQAD
        ggGBAGetueprnc7IoF7oArkKg0tSwmvsQDRNuIKSswMzAy4omnCqEcUpyaJrHOGJ
        kzKFx8mkqmjBDgXmcwjeb7OZxes0w6SAA0A2v658e8UWciG7qb6Pc9itcCfWvvOs
        3XutuW7txX/WvDdwWNKb99LBgjlZ3ChAWstgs4Kxycq+bqyEcOt9laEDxjk/u0oX
        lTL7djHsPB9hzP8TtKAA2VPXtFkDta62tnZFpJaZhnvZO8NMCtZOnrH2jouEzHSp
        /uR5eE1jC/WK6GBx7gUW1aP9eplnd2CzSJ9JnSyG/DEkhz8eTeM5jZZQHvK1sPD+
        mvqgXt39wUa1KqIujYXplhC/TYGnyAinuTLpwLnISKHDp8Nx/L6tYkmoZaYjYX4u
        Qo6s0l456K1+J3m+xnwZ57Ws0EQZxd+FDfHOW3v6G64G/eWtJK0tL5L7mZM6YJZs
        XKVzq28CqKya4ClSY5rvCI3EQYd2r6nAsyjLq5GIzS/DsStQGC+9UrIVY3RWkVoC
        WybZZA==
        -----END CERTIFICATE-----

# -----------------------------------------------------------------------------
# CLIENT AUTH – JWT authentication from backend
# -----------------------------------------------------------------------------
client_auth:
  # HMAC SHA256 key (same as backend JWT_SECRET)
  jwks:
    keys:
      - kty: oct
        alg: HS256
        kid: imu-jwt-secret
        k:
          secret: !env POWERSYNC_JWT_SECRET
